# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 15:26
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0002_auto_20170725_1343'),
        ('sede', '0002_auto_20170725_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='GradoEscalafon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grado escalafon',
                'verbose_name_plural': 'Grados escalafones',
            },
        ),
        migrations.CreateModel(
            name='NivelEducacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nivel de Educacion',
                'verbose_name_plural': 'Niveles de Educacion',
            },
        ),
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='NivelEnsenanza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nivel de ense\xf1anza',
                'verbose_name_plural': 'Niveles de ense\xf1anza',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
            },
        ),
        migrations.CreateModel(
            name='PermisosTrabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursohumano.Permiso')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sede.Sede')),
            ],
            options={
                'verbose_name': 'Permiso Trabajador',
                'verbose_name_plural': 'Permisos de trabajadores ',
            },
        ),
        migrations.CreateModel(
            name='TipoVinculacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de vinculacion',
                'verbose_name_plural': 'Tipo de vinculaciones',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.Persona')),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=150, null=True, verbose_name='Lugar de nacimiento')),
                ('celular', models.CharField(blank=True, max_length=10, null=True)),
                ('estado_civil', models.IntegerField(choices=[(1, 'Soltero/a'), (2, 'Comprometido/a'), (3, 'Casado/a'), (4, 'Divorciado/a'), (5, 'Union libre'), (6, 'Viudo/a')], verbose_name='Estado civil')),
                ('desvinculacion', models.DateField(verbose_name='Fecha de desvinculaci\xf3n')),
                ('sexo', models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino')])),
                ('areas', models.ManyToManyField(to='recursohumano.Area', verbose_name='Areas de ensenanza')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursohumano.Cargo')),
                ('escalafon_grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursohumano.GradoEscalafon', verbose_name='Grado escalafon')),
                ('exped_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sede.Departamento', verbose_name='Dpto de Expericion')),
                ('exped_municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sede.Municipio', verbose_name='Mun de Expericion')),
                ('nivel_educativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursohumano.NivelEducacion', verbose_name='Nivel educativo')),
                ('vinculacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursohumano.TipoVinculacion', verbose_name='Tipo de vinculacion')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
            },
            bases=('usuario.persona',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='permisostrabajador',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursohumano.Trabajador'),
        ),
    ]
