# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2017, verbose_name='A\xf1o')),
                ('bloqueo_periodo', models.BooleanField(choices=[(1, 'Si'), (2, 'No')], verbose_name='Inhabilitar periodo despues de cierre de fechas')),
                ('visualizacion_descriptores', models.BooleanField(choices=[(1, 'Si'), (2, 'No')], verbose_name='Visualizacion de los descriptores entre docenstes del mismo grado')),
                ('visualizacion_descriptores_nivel', models.BooleanField(choices=[(1, 'Si'), (2, 'No')], verbose_name='Visualizacion de los descriptores entre docenstes del mismo nivel educativo')),
                ('notas_docente', models.BooleanField(choices=[(1, 'Si'), (2, 'No')], verbose_name='Edicion de notas despues de ser subidas')),
                ('recuperacion_porcentaje_final', models.FloatField(default=0, verbose_name='Nota final porcentaje')),
                ('recuperacion_porcentaje_recuperacion', models.FloatField(default=0, verbose_name='Nota recuperacion porcentaje')),
                ('estudiante_boletin', models.BooleanField(choices=[(1, 'Si'), (2, 'No')], verbose_name='Habilitar impresi\xf3n de boletines a estudiantes')),
                ('director_boletin', models.BooleanField(choices=[(1, 'Si'), (2, 'No')], verbose_name='Habilitar impresi\xf3n de boletines a directores de grupos')),
            ],
            options={
                'verbose_name': 'Configuraci\xf3n',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, verbose_name='Codigo Dane')),
                ('resolucion', models.CharField(max_length=800, verbose_name='resoluci\xf3n')),
                ('telefono', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=10)),
                ('fax', models.CharField(max_length=10)),
                ('icfes', models.CharField(max_length=100, verbose_name='Codigo icfes')),
                ('sedes', models.IntegerField(verbose_name='N\xfamero de sedes')),
                ('genero', models.IntegerField(choices=[(1, 'Mixto'), (2, 'Masculino'), (3, 'Femenino')], verbose_name='Genero de poblaci\xf3n atendida')),
                ('subsidiados', models.IntegerField(choices=[(1, 'Mixto'), (2, 'Masculino'), (3, 'Femenino')], verbose_name='Ofrece cupos subsidiados')),
                ('cap_exepcionales', models.IntegerField(choices=[(1, 'Si'), (2, 'No')], verbose_name='Educaci\xf3n para capacidades excepcionales')),
                ('escudo', models.ImageField(blank=True, null=True, upload_to='avatar', verbose_name='Escudo institucion')),
                ('web', models.CharField(max_length=150, verbose_name='P\xe1gina web')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Institucion',
                'verbose_name_plural': 'Instituciones',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dane', models.CharField(max_length=100, verbose_name='Codigo Dane de la instituci\xf3n')),
                ('codigo_antiguo', models.CharField(max_length=100, verbose_name='Codigo antiguo')),
                ('consecutivo', models.CharField(max_length=100, verbose_name='Consecutivo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Consecutivo de la sede')),
                ('direccion', models.CharField(blank=True, max_length=400, null=True, verbose_name='Direcci\xf3n')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Direcci\xf3n')),
                ('estado', models.BooleanField(default=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sede.Institucion', verbose_name='Instituci\xf3n')),
                ('municipios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sede.Municipio')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.CreateModel(
            name='TipoCalendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.CreateModel(
            name='TipoJornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.CreateModel(
            name='TipoNivelacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nivelacion',
                'verbose_name_plural': 'Nivelaciones',
            },
        ),
        migrations.CreateModel(
            name='TipoRecuperacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Recuperacion',
                'verbose_name_plural': 'Recuperaciones',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
            },
        ),
        migrations.AddField(
            model_name='sede',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sede.Zona'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='calendario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sede.TipoCalendario'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sede.Departamento'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='jornadas',
            field=models.ManyToManyField(to='sede.TipoJornada', verbose_name='Tipo de jornadas'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='municipios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sede.Municipio'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sede.Sector'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sede.Zona'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sede.Institucion'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='nivelacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sede.TipoNivelacion', verbose_name='Tipo de nivelacion'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='recuperacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sede.TipoRecuperacion', verbose_name='Tipo de recuperacion'),
        ),
    ]
